/** @author kanekitakitos */

import { EventEmitter } from 'node:events';
import { ServerStatus } from './ServerStatus';
import type { NexusServer, NexusServerEvents, ServerLogLevel } from './NexusServer';

/**
 * **Base abstract Adapter** that implements most of the `NexusServer` contract,
 * leaving only `start()` and `stop()` for subclasses (the concrete Adapters like
 * HTTP, WS, gRPC, etc.).
 *
 * ## Why an abstract class (KISS + DRY)?
 *
 * Each server type has its own way of starting and stopping (binding to
 * a port, accepting connections, closing sockets…), but **all** share
 * exactly the same cross-cutting infrastructure:
 *
 * 1. Storing the current state (`_status`) and the last error (`_lastError`).
 * 2. Ensuring that a state transition emits the `statusChange` event.
 * 3. Prefixing logs with the server name and emitting the `log` event.
 * 4. Implementing `dispose()` safely (tries to stop, swallows errors,
 *    removes listeners).
 * 5. Extending `EventEmitter` so that `on/off/once` work out-of-the-box.
 *
 * Without this base class, each concrete Adapter would repeat ~50 identical lines
 * — and inevitably one of them would forget to remove listeners in `dispose`
 * or to emit `statusChange`, causing subtle bugs.
 *
 * ## Why Ports & Adapters here?
 *
 * - The `NexusServer` interface is the **Port**.
 * - This `BaseNexusServer` is an **"incomplete Adapter"** or "base superclass"
 *   that solves 80% of the concrete Adapter's work.
 * - A subclass like `ExpressHttpServer extends BaseNexusServer` is the
 *   **complete Adapter**, closing the bridge between the Port contract and the
 *   real library/framework (Express, in the example).
 *
 * Visual composition:
 * ```
 *   NexusServer (Port)  <── BaseNexusServer (abstract Adapter)  <── ExpressHttpServer (concrete Adapter)
 * ```
 */
export abstract class BaseNexusServer extends EventEmitter implements NexusServer {
  private _status: ServerStatus = ServerStatus.STOPPED;
  private _lastError: string | undefined;

  /**
   * Creates a new base server instance.
   *
   * Note that the constructor only initializes internal state — it does **not** start
   * any external resources (sockets, ports, etc.). That falls exclusively to
   * `start()`. This design (KISS) prevents constructor failures from leaving
   * objects in a partially initialized state.
   *
   * @param id - Unique server identifier. Two instances with the same
   *   `id` in the `ServerManager` cause undefined behavior.
   * @param name - Human-friendly name for UI and logs; it is automatically
   *   prefixed to all log messages generated by `this.log()`.
   * @param port - Target TCP/UDP port. The base class does **not** validate
   *   port availability — that is the responsibility of the concrete `start()`.
   */
  public constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly port: number,
  ) {
    super();
  }

  /**
   * Current state of the server lifecycle.
   *
   * @returns The current `ServerStatus` value (never `undefined`).
   * @see ServerStatus - for the complete list of possible states.
   */
  public get status(): ServerStatus {
    return this._status;
  }

  /**
   * Last error message that caused (or accompanied) a transition to the
   * `ERROR` state.
   *
   * @returns The error message as a `string`, or `undefined` if the server
   *   has never entered `ERROR` (or if it has recovered, although recovery from
   *   `ERROR` is not part of the standard cycle).
   */
  public get lastError(): string | undefined {
    return this._lastError;
  }

  /**
   * Starts the server.
   *
   * The concrete implementation **must**:
   * - Call `this.setStatus(ServerStatus.STARTING)` at the beginning.
   * - Bind to the port and open external resources.
   * - Call `this.setStatus(ServerStatus.RUNNING)` when ready.
   * - On failure, call `this.setStatus(ServerStatus.ERROR, msg)` and
   *   **then** throw the error (or Promise reject) with the same message.
   *
   * @see BaseNexusServer.setStatus - for the correct way to change state.
   */
  public abstract start(): Promise<void>;

  /**
   * Stops the server gracefully.
   *
   * The concrete implementation **must**:
   * - Call `this.setStatus(ServerStatus.STOPPING)` at the beginning.
   * - Close sockets, connections and resources. Wait for in-flight requests
   *   to finish (if applicable).
   * - Call `this.setStatus(ServerStatus.STOPPED)` when everything is closed.
   * - On failure, call `this.setStatus(ServerStatus.ERROR, msg)` and
   *   throw/reject.
   */
  public abstract stop(): Promise<void>;

  /**
   * Releases all server resources in a terminal and safe manner.
   *
   * ### Internal flow:
   * 1. If the server is **not** already `STOPPED` or `ERROR`, tries to call
   *    `stop()` to perform a graceful shutdown.
   * 2. Any error from `stop()` is **silently swallowed**. The goal of
   *    `dispose` is to clean up, not propagate failures — if `stop` failed, there
   *    is nothing more to do anyway.
   * 3. **Side effect:** Removes **all** listeners (`removeAllListeners`)
   *    to avoid memory leaks when a `ServerManager` keeps many
   *    short-lived instances.
   *
   * @returns A Promise that **always** resolves (never rejects).
   */
  public async dispose(): Promise<void> {
    if (this._status !== ServerStatus.STOPPED && this._status !== ServerStatus.ERROR) {
      try {
        await this.stop();
      } catch {
        // swallow on dispose; we are cleaning up
      }
    }
    this.removeAllListeners();
  }

  /**
   * Updates the server's internal state and notifies observers.
   *
   * **Why a protected method instead of subclasses writing
   * `this._status = ServerStatus.RUNNING` directly (KISS)?**
   * Because changing state **always** involves 4 steps and it is very easy
   * to forget one:
   *
   * 1. Check if the state actually changed (idempotency, don't emit duplicate events).
   * 2. Update `_status` and `_lastError`.
   * 3. Emit `statusChange` to whoever is listening.
   * 4. If the new state is `ERROR`, also log the message automatically.
   *
   * By centralizing this in a single method, subclasses only need to call
   * `this.setStatus(ServerStatus.RUNNING)` — the rest always happens the same way.
   *
   * @param status - New `ServerStatus` state.
   * @param errorMessage - Detailed error message. Required when
   *   `status === ERROR`, ignored (but stored) in other cases.
   *
   * **Side effects:**
   * - Updates `this._status` and `this._lastError`.
   * - Emits the `statusChange` event if there was an actual state or error change.
   * - If `status === ERROR` and `errorMessage` was provided, also emits
   *   the `log` event with `error` level.
   */
  protected setStatus(status: ServerStatus, errorMessage?: string): void {
    if (this._status === status && this._lastError === errorMessage) return;
    this._status = status;
    this._lastError = errorMessage;
    this.emit('statusChange' as keyof NexusServerEvents, status, errorMessage);
    if (status === ServerStatus.ERROR && errorMessage) {
      this.log('error', errorMessage);
    }
  }

  /**
   * Emits a log line, automatically prefixed with `[${this.name}]`.
   *
   * Subclasses should **always** use `this.log()` instead of
   * `console.log()` directly. This ensures that:
   * - All output is capturable by whoever subscribes to `server.on('log', ...)`.
   * - All output has the server name as a prefix, for readable
   *   multi-server logs.
   * - Severity (`debug`, `warn`, etc.) is preserved for filtering.
   *
   * @param level - Log severity level (see `ServerLogLevel`).
   * @param message - Log message text.
   *
   * **Side effect:** Emits the `log` event with `(level, `[${name}] ${message}`)`.
   */
  protected log(level: ServerLogLevel, message: string): void {
    this.emit('log' as keyof NexusServerEvents, level, `[${this.name}] ${message}`);
  }
}
