/** @author kanekitakitos */

import type { ServerStatus } from './ServerStatus';

/**
 * Typed map of events emitted by any `NexusServer` implementation.
 *
 * **Why a named tuple map (KISS):**
 * - Each entry defines the event name and the exact listener signature.
 *   TypeScript validates at compile time that we never subscribe to a non-existent
 *   event or pass wrong arguments to a handler.
 * - Naming the parameters inside the tuple (`status:` instead of just
 *   `[ServerStatus, string?]`) makes errors and autocomplete much clearer
 *   for API consumers.
 */
export interface NexusServerEvents {
  /** Emitted whenever the server lifecycle transitions state. */
  statusChange: [status: ServerStatus, errorMessage?: string];
  /** Emitted for each log line generated by the server implementation. */
  log: [level: ServerLogLevel, message: string];
  /** Emitted WHENEVER the server's MUTABLE runtime state changes.
   *  Used to refresh real-time UIs (TreeView, dashboards) without polling.
   *  Ex.: TFTP transfer progress, DHCP lease bound/renewed/released.
   *  No state payload — subscribers request snapshot/getServiceRuntime afterwards.
   *  `final` marks a terminal change (transfer completed/failed, lease released):
   *  the entry has just left the runtime, so consumers that coalesce updates
   *  must deliver this one instead of folding it into a later window.
   */
  runtimeUpdate: [final?: boolean];
  /** Emitted once per client-facing connection lifecycle event. See
   *  {@link ServerConnectionEvent} for what does and does not qualify. */
  connection: [event: ServerConnectionEvent];
}

/**
 * Where a connection sits in its lifecycle.
 *
 * - `started`   — a client just began something: a TFTP transfer opened, a
 *                 DORA exchange produced a lease.
 * - `completed` — that same something finished successfully.
 * - `failed`    — it ended badly, and {@link ServerConnectionEvent.detail}
 *                 says why.
 */
export type ServerConnectionPhase = 'started' | 'completed' | 'failed';

/**
 * A single client-facing connection lifecycle event — one TFTP transfer or one
 * DHCP lease, at one of the three points in {@link ServerConnectionPhase}.
 *
 * **Deliberately not a progress feed.** `runtimeUpdate` already fires on every
 * TFTP progress tick, which is what a tree view wants and what a notification
 * emphatically does not: consumers of this event are expected to surface one
 * user-visible message per emission, so an adapter must emit only at the edges
 * of a lifecycle, never per packet or per block.
 *
 * `summary` is pre-formatted by the adapter because only the adapter knows the
 * protocol's vocabulary (filenames and peers for TFTP, MACs and leases for
 * DHCP); the consumer prefixes the service name and decides where it is shown.
 */
export interface ServerConnectionEvent {
  readonly phase: ServerConnectionPhase;
  /** One-line human summary, e.g. `"lease granted 192.168.2.10 to aa:bb:…"`. */
  readonly summary: string;
  /** Failure cause, when `phase === 'failed'`. */
  readonly detail?: string;
  /** Machine-readable classification of the failure, when one is available. */
  readonly code?: string;
}

/**
 * Severity levels supported by the server logging system.
 *
 * **Why a literal union instead of an `enum` (KISS):**
 * - Log levels are a universal convention (`trace` < `debug` < `info` <
 *   `warn` < `error`). A literal string union occupies fewer compiled bytes,
 *   interoperates directly with external logging libraries
 *   (Winston, Pino, etc.) without mapping, and still retains strong typing.
 */
export type ServerLogLevel = 'trace' | 'debug' | 'info' | 'warn' | 'error';

/**
 * Primary **Port** of the Hexagonal (Ports & Adapters) architecture for servers
 * within the Nexus-tools ecosystem.
 *
 * ## Why Ports & Adapters here?
 *
 * This interface defines the **contract** that **any** Nexus server must
 * fulfill, regardless of its concrete implementation:
 *
 * - An HTTP server (Express, Fastify, Hono) is an *Adapter* that implements
 *   this Port.
 * - A WebSocket server (Socket.IO, µWebSockets) is another *Adapter*.
 * - A gRPC server, a queue worker, a TCP proxy… all are Adapters
 *   that fit into this same Port.
 *
 * Practical advantages:
 * 1. **The `ServerManager` knows nothing about HTTP.** It only knows `NexusServer`.
 *    We can add new server types without touching a single line of the Manager.
 * 2. **Testability:** In Manager unit tests, we replace a real server
 *    with a mock that implements `NexusServer` — no open sockets, no
 *    waiting, no flakiness.
 * 3. **Uniformity:** Any tool built on top of this interface
 *    (CLI, UI dashboard, REST API, health checks) automatically works
 *    for *all* registered servers.
 *
 * ## Why KISS in this interface?
 *
 * Notice the **minimum contract**: only what is really needed to manage a
 * server during its lifecycle:
 *
 * - 3 read-only properties (`id`, `name`, `port`, `status`) — identification
 *   and current state.
 * - 3 asynchronous operations (`start`, `stop`, `dispose`) — the lifecycle.
 * - 3 event methods (`on`, `off`, `once`) — observation, because a
 *   server is a reactive system.
 *
 * There is no `getRouter()`, `getHttpServer()`, `getSocket()` or protocol-specific
 * methods. Those belong to the Adapters, not the Port.
 */
export interface NexusServer {
  /**
   * Unique and immutable server identifier, used by the `ServerRegistry` and
   * `ServerManager` to reference it.
   *
   * Immutable by design: if a server could change its `id` at runtime, the
   * Manager's instance `Map` would silently break.
   */
  readonly id: string;

  /**
   * Human-friendly server name, intended for UI and logs.
   * Ex.: "Main API", "Dashboard WebSockets".
   */
  readonly name: string;

  /**
   * TCP/UDP port the server listens on (or will listen on when starting).
   * Also immutable: once created, a server does not switch ports.
   */
  readonly port: number;

  /**
   * Current state of the lifecycle. Consumers should subscribe to the
   * `statusChange` event to react to transitions instead of polling.
   */
  readonly status: ServerStatus;

  /**
   * Starts the server.
   *
   * The Promise resolves when the server is in `RUNNING` state and ready to
   * accept connections/requests. Rejects if startup fails (transition to
   * `ERROR`).
   *
   * **Expected idempotency:** If the server is already `RUNNING` or
   * `STARTING`, the implementation should return immediately, without throwing
   * errors.
   *
   * @throws {Error} If an irrecoverable failure occurs during startup
   *   (port occupied, invalid credentials, etc.).
   */
  start(): Promise<void>;

  /**
   * Stops the server gracefully (graceful shutdown).
   *
   * The Promise resolves when the server has released all resources (sockets,
   * open DB connections, timers, etc.) and reached `STOPPED`. Rejects if
   * stopping fails (transition to `ERROR`).
   *
   * **Expected idempotency:** If the server is already `STOPPED` or
   * `STOPPING`, the implementation should return immediately.
   *
   * @throws {Error} If a failure occurs during graceful shutdown.
   */
  stop(): Promise<void>;

  /**
   * Releases **all** resources associated with the server, irrevocably.
   *
   * Difference from `stop()`:
   * - `stop()` stops the server but keeps it in a condition where it can be
   *   restarted.
   * - `dispose()` is terminal. After `dispose()`, calling `start()` again
   *   has undefined behavior (most Adapters will throw an error).
   *
   * **Important contract:** `dispose()` **MUST NEVER** throw — even if
   * `stop()` fails. The purpose of `dispose` is to clean up, not report. Any
   * internal error should be caught and only logged.
   *
   * **Side effects:** Removes all event listeners registered on this
   * instance, to avoid memory leaks.
   */
  dispose(): Promise<void>;

  /**
   * Subscribes to a server event.
   *
   * Follows the same semantics as Node.js `EventEmitter`, but typed with the
   * events and arguments of `NexusServerEvents`.
   *
   * @template E - Event name (key of `NexusServerEvents`).
   * @param event - Name of the event to subscribe to.
   * @param listener - Function invoked whenever the event occurs, with the
   *   corresponding typed arguments.
   * @returns The instance itself, for chaining (fluent API).
   *
   * @see off - to remove a subscription.
   * @see once - for a single-occurrence subscription.
   */
  on<E extends keyof NexusServerEvents>(
    event: E,
    listener: (...args: NexusServerEvents[E]) => void
  ): this;

  /**
   * Removes a subscription previously registered with `on` or `once`.
   *
   * @template E - Event name.
   * @param event - Name of the subscription event to remove.
   * @param listener - The **same function reference** passed to `on`/`once`.
   *   Passing a different function (even with an identical body) has no
   *   effect — this is standard EventEmitter behavior.
   * @returns The instance itself, for chaining.
   */
  off<E extends keyof NexusServerEvents>(
    event: E,
    listener: (...args: NexusServerEvents[E]) => void
  ): this;

  /**
   * Subscribes to an event for only the **next** occurrence. After the first
   * emission, the listener is automatically removed.
   *
   * Useful for one-shot operations like "notify me when the server starts
   * for the first time".
   *
   * @template E - Event name.
   * @param event - Name of the event to subscribe to.
   * @param listener - Function invoked a single time.
   * @returns The instance itself, for chaining.
   */
  once<E extends keyof NexusServerEvents>(
    event: E,
    listener: (...args: NexusServerEvents[E]) => void
  ): this;
}
