import { createHash, randomUUID } from "node:crypto";

export const INVENTORY_CONTRACT_VERSION = 1 as const;

export type InventoryEndpointKind = "ssh" | "redfish" | "url" | "ipmi-sol";

/**
 * One way to reach a device. Phase 1 only maps the FIRST endpoint with
 * kind === "ssh"; all other kinds (and extra ssh endpoints) are accepted,
 * preserved on the tree, and otherwise unused.
 */
export interface InventoryEndpoint {
  kind: InventoryEndpointKind;
  host: string; // hostname or IP, no CIDR suffix
  port?: number; // ssh default 22
  username?: string; // if set, the SOURCE owns username on the mapped server
  attributes?: Record<string, string | number | boolean>; // future kinds; ignored Phase 1
}

export interface InventoryDevice {
  externalId: string; // REQUIRED, stable across syncs, unique within one source
  name: string;
  folderPath?: string; // slash path RELATIVE to source targetFolder; ""/undefined = at targetFolder
  endpoints: InventoryEndpoint[];
}

export interface InventoryTree {
  contractVersion: 1;
  devices: InventoryDevice[];
  warnings?: string[]; // provider-side notices surfaced in plan summary
  // FIX 2 — set by a provider when it stopped collecting early because it hit
  // its own hard cap (not because the source ran out of devices). When true,
  // computeSyncPlan skips the prune phase entirely: a capped fetch must never
  // be mistaken for "these devices no longer exist at the source".
  truncated?: boolean;
}

export type InventoryConfigFieldType = "string" | "password" | "number" | "boolean";

export interface InventoryConfigField {
  id: string;
  label: string;
  type: InventoryConfigFieldType;
  required?: boolean;
  placeholder?: string;
  description?: string;
}

export type InventorySourceValues = Record<string, string | number | boolean>; // secrets NEVER here
export type InventorySourceSecrets = Record<string, string>; // from SecretStorage

export interface InventoryProvider {
  id: string; // e.g. "netbox"; unique in registry
  label: string;
  configFields: InventoryConfigField[];
  testConnection(config: InventorySourceValues, secrets: InventorySourceSecrets): Promise<void>;
  fetchInventory(config: InventorySourceValues, secrets: InventorySourceSecrets): Promise<InventoryTree>;
}

export type InventoryErrorKind = "auth" | "network" | "protocol";

export class InventoryProviderError extends Error {
  public constructor(
    public readonly kind: InventoryErrorKind,
    message: string
  ) {
    super(message);
    this.name = "InventoryProviderError";
  }
}

export type InventoryPrunePolicy = "delete" | "orphan" | "keep";

export interface InventorySourceConfig {
  id: string; // randomUUID at creation
  providerId: string;
  name: string; // user-facing
  targetFolder: string; // normalized, or "" for root (allowed, discouraged)
  prunePolicy: InventoryPrunePolicy; // default "orphan"
  defaultUsername: string; // fallback SSH username applied AT ADD TIME only
  config: InventorySourceValues; // non-secret provider config
  secretFieldIds: string[]; // password-type field ids captured at save time (for cleanup/backup independence from provider registration)
  lastSyncAt?: number;
  // FINDING 1 (removal-identity review) — opaque generation token identifying
  // which INCARNATION of this record this is. Assigned fresh by
  // NexusCore.addOrUpdateInventorySource on EVERY write (every call site —
  // addSource, editSource, backup import/restore, ... — gets a new one for
  // free without needing to remember it itself); NEVER regenerated by
  // applyInventorySyncPlan's own lastSyncAt bump, so a routine sync does not
  // by itself invalidate a caller's already-captured snapshot. Optional for
  // backward compat with records persisted before this field existed — the
  // storage layer backfills a revision for those at LOAD time (see
  // VscodeConfigRepository.getInventorySources / InMemoryConfigRepository's
  // ensureInventorySourceRevision use), never retroactively rewriting disk.
  // See sourceConfigUnchanged() below for how this decides identity once
  // both sides being compared have one.
  revision?: string;
  // ITEM A (provider trust fingerprint) — a stable hash of the PROVIDER's
  // observable shape (label + ordered configFields) at the moment this
  // source was last saved (addSource) or edited (editSource), computed by
  // computeProviderFingerprint() below. VS Code exposes no caller identity
  // for `registerInventoryProvider` (see publicApi.ts's trust-model doc), so
  // this cannot prove WHICH extension is answering to `providerId` — only
  // that the currently-registered provider's declared shape still looks like
  // the one the user last knowingly configured. syncNow compares this
  // against computeProviderFingerprint(currentRegistrant) before reading any
  // vault secret for the source; a mismatch means the id was re-registered
  // (by an update, or by a different extension entirely) with a materially
  // different provider since, and the user is asked to confirm handing that
  // registrant the saved credentials. Optional for backward compatibility —
  // a source saved before this field existed has none; syncNow stamps it
  // silently on that source's first successful sync afterward (nothing to
  // compare it against yet, so no warning is shown).
  providerFingerprint?: string;
  // REVIEW FINDING 1 (P2, folder-GC ownership) — the folder paths (strictly
  // under `targetFolder`, ancestors included) that THIS source's own syncs
  // have created/used, as of the most recent `applyInventorySyncPlan` call
  // (non-"absent" mode only). Recomputed and overwritten wholesale on every
  // such apply — it is a snapshot of "what this sync's own `folders` list
  // named", not an accumulating history — so a folder this source stops
  // naming (e.g. a renamed rack) drops out of the set on the very sync that
  // stops naming it, making it eligible for GC on that same pass.
  //
  // Exists so `pruneEmptyFoldersUnderTarget` can tell "a folder THIS source
  // created and then abandoned" (safe to GC when empty) apart from "a folder
  // that happens to be empty right now" (never safe to GC on that basis
  // alone — it could be a manually-created folder the user deliberately
  // keeps empty, like a staging area, or a folder owned by a DIFFERENT
  // source under the same targetFolder). Only paths ever present in a
  // source's own `managedFolders` are GC candidates for that source; an
  // explicit folder never named by any of this source's applies is never
  // touched, however empty it is.
  //
  // Optional for backward compatibility: a source record persisted before
  // this field existed (or one that has simply never completed a
  // non-"absent" apply) has none. `applyInventorySyncPlan` treats a missing
  // `managedFolders` as an empty set for the purpose of computing GC
  // candidates — so a legacy/first sync stamps the set for the first time
  // but removes NOTHING as a side effect of that stamping (there is no prior
  // set to diff against yet). removeSource deletes the source record
  // wholesale, so `managedFolders` dies with it — any folders it names are
  // left behind, exactly like the rest of the source's bookkeeping (this
  // mirrors the already-documented behavior of leaving synced servers'
  // folders alone on source removal).
  managedFolders?: string[];
}

/**
 * ITEM A (provider trust fingerprint) — pure hash over exactly the provider
 * shape a user can actually SEE and reason about when they configured a
 * source: its label and its configFields' (id, label, type, required),
 * in the provider's own declared order. Deliberately excludes
 * testConnection/fetchInventory (functions — not hashable, and not what the
 * user "configured against") and `id` itself (the fingerprint's whole
 * purpose is to detect a DIFFERENT provider answering to the SAME id; hashing
 * the id would make every mismatch invisible). No `vscode` import — callable
 * from models/ and safe for both the command layer and tests.
 *
 * sha256, hex-encoded, truncated to the first 16 characters — this is a
 * drift-detection fingerprint, not a security credential, so collision
 * resistance at full sha256 strength is unnecessary; 16 hex chars (64 bits)
 * is already far more than this UI-facing comparison needs.
 */
export function computeProviderFingerprint(provider: Pick<InventoryProvider, "label" | "configFields">): string {
  const shape = {
    label: provider.label,
    configFields: provider.configFields.map((field) => ({
      id: field.id,
      label: field.label,
      type: field.type,
      required: field.required === true
    }))
  };
  return createHash("sha256").update(JSON.stringify(shape)).digest("hex").slice(0, 16);
}

/**
 * SecretStorage key for one (source, field) credential.
 *
 * Name is `${sourceId.length}:${sourceId}:${fieldId}` — mirroring
 * deterministicServerId's scheme — rather than a bare
 * `sourceId-fieldId` concatenation: sourceId is a user-editable inventory
 * source id (not guaranteed `-`-free like a randomUUID), so without a length
 * prefix two different (sourceId, fieldId) splits of the same joined string
 * could collide (e.g. "a-b" + "c" vs "a" + "b-c").
 *
 * fieldId itself does NOT need its own length prefix: the sourceId length
 * prefix already pins the exact split point (read the digits up to the
 * first `:`, then take exactly that many characters as sourceId, then the
 * next `:`), so everything after that second `:` is unambiguously fieldId
 * — even if fieldId itself contains further `:` or `-` characters. Putting
 * fieldId last (rather than first) is what makes this work with only one
 * length prefix.
 */
export function inventorySecretKey(sourceId: string, fieldId: string): string {
  return `inventory-source-${sourceId.length}:${sourceId}:${fieldId}`;
}

/**
 * FINDING 1 — assigns a revision to a source record loaded from persisted
 * storage that predates the `revision` field (a "legacy" record). Called by
 * the repository getters at LOAD time only — never by NexusCore, which
 * regenerates a revision on every WRITE instead (see
 * NexusCore.addOrUpdateInventorySource). Returns the input unchanged (same
 * reference) when a revision is already present, so this is safe to map over
 * every loaded record unconditionally.
 */
export function ensureInventorySourceRevision(source: InventorySourceConfig): InventorySourceConfig {
  return source.revision ? source : { ...source, revision: randomUUID() };
}

/**
 * Exported (not just used by sourceConfigUnchanged below) because
 * inventoryCommands.ts's syncNow also uses it directly to compare the vault
 * secret values captured at fetch time against a re-read taken immediately
 * before apply (FINDING D) — InventorySourceSecrets is structurally a
 * Record<string, string>, a subtype of InventorySourceValues, so this
 * comparator works for both.
 */
export function inventorySourceValuesEqual(a: InventorySourceValues, b: InventorySourceValues): boolean {
  const aKeys = Object.keys(a);
  const bKeys = Object.keys(b);
  if (aKeys.length !== bKeys.length) return false;
  return aKeys.every((key) => Object.prototype.hasOwnProperty.call(b, key) && a[key] === b[key]);
}

function secretFieldIdsEqual(a: readonly string[], b: readonly string[]): boolean {
  if (a.length !== b.length) return false;
  const sortedA = [...a].sort();
  const sortedB = [...b].sort();
  return sortedA.every((id, i) => id === sortedB[i]);
}

/**
 * FINDINGS D/E — compares exactly the InventorySourceConfig fields that feed
 * computeSyncPlan/planToApplication (and the fetchInventory config; secret
 * VALUES are compared separately against the vault — see
 * inventoryCommands.ts's post-teardown check, which core cannot perform
 * itself since it has no vault access). A source record that differs on any
 * of these must not have a tree fetched under the OLD config applied against
 * it, even though its id still exists — e.g. a replace-mode config import can
 * delete and recreate the same source id with an entirely different provider
 * config while a sync is mid-flight.
 *
 * Lives here (not in commands or core) so both `NexusCore.applyInventorySyncPlan`
 * (the atomic, pre-mutation guard) and `inventoryCommands.ts`'s earlier
 * fast-fail checks share one comparator — core must not import from commands.
 *
 * FINDING 1 (removal-identity review) — structural equality alone cannot
 * prove two InventorySourceConfig values are the SAME record incarnation: a
 * replace-mode import can recreate a record with an identical
 * name/providerId/targetFolder/prunePolicy/defaultUsername/config/
 * secretFieldIds while pointing the same field ids at a brand-new vault
 * credential. When BOTH sides carry a `revision` (see the field doc), it
 * REPLACES the structural comparison entirely: equal revisions mean the same
 * incarnation (a legitimate lastSyncAt bump from applyInventorySyncPlan never
 * changes revision, so this still holds true across one), and different
 * revisions mean a different incarnation even when every structural field
 * happens to still match. Only when either side predates the revision field
 * (a legacy record) does this fall back to the old field-by-field structural
 * comparison — the same one used before this finding.
 */
export function sourceConfigUnchanged(a: InventorySourceConfig, b: InventorySourceConfig): boolean {
  if (a.revision !== undefined && b.revision !== undefined) {
    return a.revision === b.revision;
  }
  return (
    a.providerId === b.providerId &&
    a.targetFolder === b.targetFolder &&
    a.prunePolicy === b.prunePolicy &&
    a.defaultUsername === b.defaultUsername &&
    inventorySourceValuesEqual(a.config, b.config) &&
    secretFieldIdsEqual(a.secretFieldIds, b.secretFieldIds)
  );
}
